config/routes.rb
Vigor::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get "registrations/create"

  resources :vrhighlights

  resources :attachments

  resources :attatchments

  resources :restaurants

  resources :vegresources
  
  resources :home do
    collection do
      get 'send_email2list'
      get 'my_mailer'
      post 'send_email2list'
      post 'my_mailer'
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  
  devise_for :users, :controllers => { :registrations => "registrations" } do
    
   get "login", :to => "devise/sessions#new"
   delete "logout", :to => "devise/sessions#destroy"
   get "signup", :to => "devise/registrations#new"
   
  end
  
  resources :users do
   member do
     get 'removephoto'
     put 'addphoto'
     post 'addphoto'
   end
  end
  
  match "/users/:id/addphoto" => "users#addphoto", :via => [:post]
  match "/listrecipes/:by/:attr" => "recipes#list", :via => [:get]
  
  resources :events do
    collection do
      get 'calendar'
      post 'calendar'
      get 'copy'
      post 'list'
    end
    member do
      get 'review'
    end
  end

  resources :posts do
    collection do
      post 'comment'
      get 'comment'


    end
  end 
  resources :categories
  
  resources :recipes do
    with_scope_level(:list) do
      get 'list/:category', :to => "recipes#list"
    end
    
    member do
      get 'review'
    end
  end
  
  resources :lists

  resources :friends do
  collection do
   get 'list'
   post 'list'
  end
  end


  resources :list_cats
  resources :vrattributes
  
  resources :reviews, :except => [:new,:index] do   
    with_scope_level(:new) do
      get 'new/:toreview', :to => "reviews#new"
   end
    with_scope_level(:index) do
      get 'index/:reviewed', :to => "reviews#index"
   end
   
   member do
     get 'edit'
   end
 end
  
  resources :vegresources, :except => [:new] do   
    with_scope_level(:new) do
      get 'new/:vrtype', :to => "vegresources#new"
   end
    
    member do
      get 'review'
      get 'highlight'
    end
 end

  match '/books'  => 'vegresources#books'
  match '/videos' => 'vegresources#videos'
  match '/websites' => 'vegresources#websites'
  match '/csas' => 'vegresources#csas'
  match '/grocery' => 'vegresources#grocery'
  match '/ristorantes' => 'vegresources#restaurants'
    
  match '/contact' => 'home#contact'
  
end

app/models/list.rb
class List < ActiveRecord::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  # GET /lists
  # GET /lists.xml
  def index
    @lists = List.find(:all)
    @list_cats = ListCat.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.xml
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.xml
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.xml
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        flash[:notice] = 'List was successfully created.'
        format.html { redirect_to(:controller => 'lists') }
        format.xml  { render :xml => @list, :status => :created, :location => @list }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.xml
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        flash[:notice] = 'List was successfully updated.'
        format.html { redirect_to(:controller => 'lists') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.xml
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => 'lists')}
      format.xml  { head :ok }
    end
  end
end

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= form_for(@list) do |f| %>
  <p>
    <b>Friend</b><br />
    <%= f.text_field :friend_id %>
  </p>

  <p>
    <b>List cat</b><br />
    <%= f.text_field :list_cat_id %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Contacts Query Page', friends_path %> &nbsp; &nbsp; &nbsp; &nbsp;
<%= link_to 'Administer Contact lists', :controller => 'lists'%>

app/views/lists/index.html.erb
<h1>Contact Lists</h1>

<table>

<% for alist_cat in @list_cats %>
  <tr>
    <td><%=h alist_cat.name %></td>
	<td><%=h alist_cat.description %></td>
    <td><%= link_to 'Edit', edit_list_cat_path(alist_cat) %></td>
    <td><%= link_to 'Remove', alist_cat, :controller => 'list_cats', :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New list', new_list_cat_path %> &nbsp; &nbsp; &nbsp; &nbsp;
<%= link_to 'Contacts Query Page', friends_path %> &nbsp; &nbsp; &nbsp; &nbsp;
<%= link_to 'Administer Contact lists', :controller => 'lists'%>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= form_for(@list) do |f| %>
  <p>
    <b>Friend</b> - If parms doesn't provide contact name, list contacts in checkboxes.<br />
    <%= f.text_field :friend_id , :value => params["friend_id"]%>
  </p>

  <p>
    <b>List cat</b> - If parms doesn't provide list name, list categories in check boxes.<br />
    <%= f.text_field :list_cat_id, :value => params["list_cat"]["category_id"] %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Contacts Query Page', friends_path %> &nbsp; &nbsp; &nbsp; &nbsp;
<%= link_to 'Administer Contact lists', :controller => 'lists'%>

app/views/lists/show.html.erb
<p>
  <b>Friend:</b>
  <%=h @list.friend_id %>
</p>

<p>
  <b>List cat:</b>
  <%=h @list.list_cat_id %>
</p>


<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>