config/routes.rb
Vigor::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get "registrations/create"

  resources :vrhighlights

  resources :attachments

  resources :attatchments

  resources :restaurants

  resources :vegresources
  
  resources :home do
    collection do
      get 'send_email2list'
      get 'my_mailer'
      post 'send_email2list'
      post 'my_mailer'
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  
  devise_for :users, :controllers => { :registrations => "registrations" } do
    
   get "login", :to => "devise/sessions#new"
   delete "logout", :to => "devise/sessions#destroy"
   get "signup", :to => "devise/registrations#new"
   
  end
  
  resources :users do
   member do
     get 'removephoto'
     put 'addphoto'
     post 'addphoto'
   end
  end
  
  match "/users/:id/addphoto" => "users#addphoto", :via => [:post]
  match "/listrecipes/:by/:attr" => "recipes#list", :via => [:get]
  
  resources :events do
    collection do
      get 'calendar'
      post 'calendar'
      get 'copy'
      post 'list'
    end
    member do
      get 'review'
    end
  end

  resources :posts do
    collection do
      post 'comment'
      get 'comment'


    end
  end 
  resources :categories
  
  resources :recipes do
    with_scope_level(:list) do
      get 'list/:category', :to => "recipes#list"
    end
    
    member do
      get 'review'
    end
  end
  
  resources :lists

  resources :friends do
  collection do
   get 'list'
   post 'list'
  end
  end


  resources :list_cats
  resources :vrattributes
  
  resources :reviews, :except => [:new,:index] do   
    with_scope_level(:new) do
      get 'new/:toreview', :to => "reviews#new"
   end
    with_scope_level(:index) do
      get 'index/:reviewed', :to => "reviews#index"
   end
   
   member do
     get 'edit'
   end
 end
  
  resources :vegresources, :except => [:new] do   
    with_scope_level(:new) do
      get 'new/:vrtype', :to => "vegresources#new"
   end
    
    member do
      get 'review'
      get 'highlight'
    end
 end

  match '/books'  => 'vegresources#books'
  match '/videos' => 'vegresources#videos'
  match '/websites' => 'vegresources#websites'
  match '/csas' => 'vegresources#csas'
  match '/grocery' => 'vegresources#grocery'
  match '/ristorantes' => 'vegresources#restaurants'
    
  match '/contact' => 'home#contact'
  
end

app/models/vegresource.rb
class Vegresource < ActiveRecord::Base
  has_many :reviews, :dependent => :destroy
  has_many :attachments, :dependent => :destroy
  has_many :vrhighlights, :dependent => :destroy
  #has_many :vraas, :dependent => :destroy
  #has_many :vrattributes, :through => :vraas
  has_and_belongs_to_many :vrattributes
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  accepts_nested_attributes_for :reviews, :allow_destroy => true
  accepts_nested_attributes_for :vrhighlights, :allow_destroy => true
  belongs_to :user #user that submitted the resource
  attr_accessible :vrtype ,:name, :website, :author, :info, :address, :vrattributes, :vrhighlights_attributes, :vrattribute_ids, :attachments_attributes, :reviews_attributes

  def rating
    reviews.select("avg(rating) as average").first.average.to_i
  end
  
end

app/controllers/vegresources_controller.rb
class VegresourcesController < ApplicationController
    before_filter :authenticate_user!, :only => [ :edit, :new, :update, :review, :highlight ]
    load_and_authorize_resource
    layout '/layouts/vegresources'
  # GET /vegresources
  # GET /vegresources.json
  def index
  end
  
  def restaurants
    @restaurants = Vegresource.where("vrtype = 'restaurant'")
    @vrtype = 'restaurant'

    respond_to do |format|
      format.html # index.html.erb
    #  format.json { render :json => @restaurants }
    end
  end
  
    def csas
    @csas = Vegresource.where("vrtype = 'csa'")
    @vrtype = 'csa'

    respond_to do |format|
      format.html # index.html.erb
   #   format.json { render :json => @csas }
    end
  end

  def grocery
    @grocers = Vegresource.where("vrtype = 'grocer'")
    @vrtype = 'grocer'

    respond_to do |format|
      format.html # index.html.erb
    #  format.json { render :json => @grocers}
    end
  end
  
    def books
    @books = Vegresource.where("vrtype = 'book'")
    @vrtype = 'book'

    respond_to do |format|
      format.html # index.html.erb
    #  format.json { render :json => @grocers}
    end
  end
  
    def videos
    @videos = Vegresource.where("vrtype = 'video'")
    @vrtype = 'video'
    

    respond_to do |format|
      format.html # index.html.erb
    #  format.json { render :json => @grocers}
    end
  end
  
    def websites
    @websites = Vegresource.where("vrtype = 'website'")
    @vrtype = 'website'

    respond_to do |format|
      format.html # index.html.erb
     # format.json { render :json => @grocers}
    end
  end



  # GET /vegresources/1
  # GET /vegresources/1.json
  def show
    @vegresource = Vegresource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
     # format.json { render :json => @vegresource }
    end
  end

  # GET /vegresources/new
  # GET /vegresources/new.json
  def new
    @vegresource = Vegresource.new
    @vrtype = params[:vrtype]
    respond_to do |format|
      format.html # new.html.erb
     # format.json { render :json => @vegresource }
    end
  end

  # GET /vegresources/1/edit
  def edit
    @vegresource = Vegresource.find(params[:id])
    @vrtype = @vegresource.vrtype
  end
  
   # GET /vegresources/1/review
  def review
    @vegresource = Vegresource.find(params[:id])
  end
   
    def highlight
    @vegresource = Vegresource.find(params[:id])
    @vrhighlight = @vegresource.vrhighlights.create
  end
  
   def vrattributes
  vrattribute = Vrattribute.find_by_name(name)
     # Vrattribute_assignment.create(:vrattribute_id => vrattribute, :vegresource_id => @vegresource) unless Vrattribute_assignment.where("vrattribute_id = ? AND vegresource_id = ?",vrattribute.id,@vegresource)
   # end
  
      respond_to do |format|
        format.html{ render_text output}
        format.html { redirect_to @vegresource, :notice => 'Attributes successfully added.' }
      #  format.json { render :json => @vegresource, :status => :created, :location => @vegresource }
    
    end
  end

  # POST /vegresources
  # POST /vegresources.json
  def create
    @vegresource = Vegresource.new(params[:vegresource])
    @vegresource.user_id = current_user.id
    respond_to do |format|
      if @vegresource.save
        format.html { redirect_to @vegresource, :notice => 'Vegresource was successfully created.' }
      #  format.json { render :json => @vegresource, :status => :created, :location => @vegresource }
      else
        format.html { render :action => "new" }
       # format.json { render :json => @vegresource.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vegresources/1
  # PUT /vegresources/1.json
  def update
    @vegresource = Vegresource.find(params[:id])
    
    ################################################################################
    # Create attribute assignements for all that were checked for this resource 
    # and delete any that were previously assigned, but currently unchecked
    ################################################################################
    # 1.a If attribute boxes were checked
    #if params[:vrattributes]
    #  checkedattributes = params[:vrattributes]
      
      # 2. Walk through all attributes for this resource type
    #  Vrattribute.where(:vrtype => @vegresource.vrtype).each do |vrattribute| 
     #   currentlyassigned = Vraa.where("vrattribute_id = ? AND vegresource_id = ?",vrattribute.id,@vegresource.id.to_s)
 
        # 3.a Remove the attribute from this resource if it's currently assigned and unchecked
     #   if (currentlyassigned && checkedattributes.include?(vrattribute.name).blank? ) 
    #      @vegresource.vraas.delete(currentlyassigned)

        # 3.b Otherwise assign this attribute if it's checked
    #    elsif checkedattributes.include?(vrattribute.name)       
    #     Vraa.create(:vrattribute_id => vrattribute.id, :vegresource_id => @vegresource.id)
    #    end
    #  end
      
    # 1.b If nothing was checked make sure any remaining are unassigned
  #  elsif Vraa.where(:vegresource_id => @vegresource.id)
   #   Vraa.where(:vegresource_id => @vegresource.id).each do |remaining|
   #     @vegresource.vraas.delete(remaining)
   #   end
  #  end
    ##################################################################################
    respond_to do |format|
      if @vegresource.update_attributes(params[:vegresource])
        format.html { redirect_to @vegresource, :notice => 'Vegresource was successfully updated.' }
      #  format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        #format.json { render :json => @vegresource.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vegresources/1
  # DELETE /vegresources/1.json
  def destroy
    @vegresource = Vegresource.find(params[:id])
    @vegresource.destroy

    respond_to do |format|
      format.html { redirect_to vegresources_url }
     # format.json { head :no_content }
    end
  end
end

app/helpers/vegresources_helper.rb
module VegresourcesHelper
end

app/views/vegresources/_form.html.erb
<%= simple_form_for(@vegresource) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.hidden_field :vrtype, :value => @vrtype%>
    <% capvrtype = @vrtype; capvrtype[0] = capvrtype[0].to_s.capitalize %>
    <%= f.input :name, :label => capvrtype + ' name'%>
    <%= f.input :website %>
    <%= f.input :author if @vrtype == 'book'%>
    <%= f.input :address if ['restaurant','store'].include?(@vrtype)%>
    <%= f.input :info, :label => 'Information' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Submit', :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/vegresources/_listitem.html.erb
<div class="row-fluid content" >
	  <span class="span2"><%= link_to(image_tag(vr.attachments.first.photo.url(:small), :style => "width: 100%"), vr) unless vr.attachments.blank? %></span>
	  <span class="span4"><% vr.rating.times do%><%=image_tag('/assets/star.jpg',:style => "width:2.5em")%> <%end%>(<%=vr.reviews.size%> reviews)<h4><%= link_to vr.name,vr %></h4><%= vr.info %></span>
	  <span class="span4">
	  <% vr.vrhighlights.order("created_at DESC").limit(3).each do |highlight| %>
       <div class="container-fluid btn btn-large" style="width:80%;margin-right:2em;font-size:.8em">
       	<%= image_tag(highlight.attachments.first.photo.url(:thumb),:style => "height:3em") unless highlight.attachments.blank? %> <%= highlight.name %>
        $<%= highlight.price%> on <%=highlight.date_observed%>
       </div>
     <% end %>	
	  </span>
	  <span class="span2">
	  <%if can? :create, Vegresource%>
	    <%= link_to 'Edit', edit_vegresource_path(vr), :class => "btn" %>
	    <%= link_to '<i class="icon-white icon-trash"></i>'.html_safe, vr, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger" %>
      <%end%>
	  </span>
  </div>

app/views/vegresources/_vraform.html.erb
 <script type="text/javascript">                                         
   $(document).ready(function() {
      $("a#colapse").click(function() {
     $("#veg-resource-<%= vegresource.id %>").toggle();
   });

 });                                 
 </script> 
 <a id="colapse" class="btn btn-warning" href="#">Change Attributes</a>
<div id="veg-resource-<%= vegresource.id %>" class="modal" style="display:none;postion:absolute" >
  <%= simple_form_for vegresource, :url => vegresource_path(vegresource), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Update Attributes</h3>
    </div>
    <div class="modal-body">
      <%= f.input :vrattribute_ids, :collection => Vrattribute.where(:vrtype => vegresource.vrtype), :as => :check_boxes, :label_method => lambda {|t| t.name}, :label => false, :item_wrapper_class => 'inline', :checked =>  lambda {|t| !t.vegresources.find_by_id(vegresource.id).nil?} %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Update Attributes", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/vegresources/books.html.erb
<h1 class="title" style="margin: 0 -.4em;padding: .1em .4em">Books</h1>

<% @books.each do |vr| %>
<%=render :partial => '/vegresources/listitem', :locals => {:vr => vr}%>
 
<% end %>

<br />
<% if can? :create, Vegresource %>
<%= link_to 'New Book', new_vegresource_path(:vrtype => 'book'),:class => "btn btn-primary" %>
<%end%>

app/views/vegresources/csas.html.erb
<h1 class="title" style="margin: 0 -.4em;padding: .1em .4em">Community Supported Agrigulture</h2>


<% @csas.each do |vr| %>

<%=render :partial => '/vegresources/listitem', :locals => {:vr => vr}%>
<% end %>


<br />
<% if can? :create, Vegresource %>
<%= link_to 'New CSA', new_vegresource_path(:vrtype => 'csa'),:class => "btn btn-primary" %>
<%end%>

app/views/vegresources/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @vegresource %> |
<%= link_to 'Back', vegresources_path %>

app/views/vegresources/grocery.html.erb
<h1 class="title" style="margin: 0 -.4em;padding: .1em .4em">Grocery Stores</h1>

<% @grocers.each do |vr| %>
<%=render :partial => '/vegresources/listitem', :locals => {:vr => vr}%>
  
<% end %>

<br />
<% if can? :create, Vegresource%>
<%= link_to 'Add Grocer', new_vegresource_path(:vrtype => 'grocer'),:class => "btn btn-primary" %>
<%end%>

app/views/vegresources/highlight.html.erb
Highlight an item for this <%=@vegresource.vrtype%>
<%= render :partial => '/vrhighlights/form', :locals => {:object => @vegresource} %>

app/views/vegresources/index.html.erb
<h2>Vegetarian Resources</h2>
Rochester Minnesota Vegetarian community contributed resource listings, highlists and reviews.
<ul>
<li><%= link_to 'Grocery Guide', grocery_path %> </li>
<li><%= link_to 'Restaurant Guide', ristorantes_path %></li>
<li><%= link_to 'Books',    books_path %></li>
<li><%= link_to 'Videos',     videos_path %></li>
<li><%= link_to 'Websites',   websites_path %> </li>
<li><%= link_to 'Rochester Area Community Supported Agriculture',  csas_path %> </li>
</ul>

app/views/vegresources/new.html.erb
<h1>New <%=@vrtype%> </h1>

<%= render 'form' %>

<%= link_to 'Back', vegresources_path %>

app/views/vegresources/restaurants.html.erb
<h1 class="title" style="margin: 0 -.4em;padding: .1em .4em">Restaurants</h1>

<% @restaurants.each do |vr| %>
<%=render :partial => '/vegresources/listitem', :locals => {:vr => vr}%>
<% end %>

<br />
<% if can? :create, Vegresource %>
<%= link_to 'New Restaurant', new_vegresource_path(:vrtype => 'restaurant'),:class => "btn btn-primary" %>
<%end%>

app/views/vegresources/review.html.erb
Review <%=@vegresource.name%>
<%= render :partial => '/reviews/form', :locals => {:object => @vegresource} %>

app/views/vegresources/show.html.erb
<!-- ############### -->
<!-- Resource Fields -->
<!-- ############### -->
<div class="row-fluid">
<span class="span6">
<h2 class="title"><%= @vegresource.name %></h2>  
<%=render :partial => '/layouts/like', :locals => {:likeurl => vegresource_url(@vegresource)}%>

 <p><%= @vegresource.website %></p>
 <p><%= @vegresource.author %></p>
 <p><%= @vegresource.address %></p>
 <p><%= @vegresource.info %></p>
 
 <% if ['restaurant','grocer'].include?(@vegresource.vrtype)%>
 </span>

<!-- ############### -->
<!--<h2> Images </h2> -->
<!-- ############### -->
<span class="span6">
	
<%= render :partial => '/attachments/view', :locals => {:object => @vegresource} %>
<% if can? :create, Vegresource %>
<%= render :partial => '/attachments/form', :locals => {:object => @vegresource} %>
<%end%>

 <% if ['restaurant','grocer'].include?(@vegresource.vrtype)%>
</span>
</div>

<!-- ###############    -->
<!-- <h2> Details </h2> -->
<!-- ###############    -->

<% if can? :create, Vegresource  %>	
<%= render :partial => 'vraform', :locals => {:vegresource => @vegresource} %>
<% end %>
  <div class="row-fluid content">
   <% @vegresource.vrattributes.each do |vrattribute| %>
     <span class="span2"><%= vrattribute.name %> </span>
      <% end %>
  </div>
<% end %>

<!-- ############### -->
<!-- Menu Links -->
<!-- ############### -->
<div>
<% if can? :create, Vegresource  %>	
<%= link_to 'Edit entry for ' + @vegresource.name, edit_vegresource_path(@vegresource), :class => "btn" %> 
<%= link_to 'Create New Attribute Type for ' + @vegresource.vrtype, new_vrattribute_path, :class => "btn"  %> 
<% end %>
</div>


<div class="row-fluid">
<span class="span5">
<!-- ############### -->
<h2>Highlights</h2>  
<!-- ############### -->
<% if can? :create, Vegresource %>
<p><%= link_to 'Highlight Item', highlight_vegresource_path(@vegresource), :class => "btn btn-primary" %></p>
<% elsif !user_signed_in? %>
<%= render :partial => '/users/signup', :locals => {:message => "to get access to highlight " + @vegresource.vrtype + " items."}%>
<%end%>
<% @vegresource.vrhighlights.each do |highlight| %>
<div class="container-fluid content" style="margin-right:2em">
<%= render :partial => '/vrhighlights/show', :locals => {:vrhighlight => highlight} %>
</div>
<% end %>
<% end %>
</span>
<span class="span1"></span>
<span class="span5">
<!-- ############### -->
<h2>Reviews</h2>
<!-- ############### -->

<% if can? :create, Vegresource %>
<p><%= link_to 'Write Review', review_vegresource_path(@vegresource), :class => "btn btn-primary"  %></p>
<% elsif !user_signed_in? %>
<%= render :partial => '/users/signup', :locals => {:message => "to get access to review " + @vegresource.vrtype + "s."}%>
<%end%>
<% @vegresource.reviews.each do |review| %>
<div class="container-fluid content" style="margin-left:0">
<%= render :partial => '/reviews/show', :locals => {:review => review} %>
</div>
<% end %>
</span>
</div>

app/views/vegresources/videos.html.erb
<h1 class="title" style="margin: 0 -.4em;padding: .1em .4em">Videos</h1>

<% @videos.each do |vr| %>
<%=render :partial => '/vegresources/listitem', :locals => {:vr => vr}%>
<% end %>

<br />
<% if can? :create, Vegresource %>
<%= link_to 'Add Video Listing', new_vegresource_path(:vrtype => 'video'),:class => "btn btn-primary" %>
<%end%>