config/routes.rb
Vigor::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get "registrations/create"

  resources :vrhighlights

  resources :attachments

  resources :attatchments

  resources :restaurants

  resources :vegresources
  
  resources :home do
    collection do
      get 'send_email2list'
      get 'my_mailer'
      post 'send_email2list'
      post 'my_mailer'
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  
  devise_for :users, :controllers => { :registrations => "registrations" } do
    
   get "login", :to => "devise/sessions#new"
   delete "logout", :to => "devise/sessions#destroy"
   get "signup", :to => "devise/registrations#new"
   
  end
  
  resources :users do
   member do
     get 'removephoto'
     put 'addphoto'
     post 'addphoto'
   end
  end
  
  match "/users/:id/addphoto" => "users#addphoto", :via => [:post]
  match "/listrecipes/:by/:attr" => "recipes#list", :via => [:get]
  
  resources :events do
    collection do
      get 'calendar'
      post 'calendar'
      get 'copy'
      post 'list'
    end
    member do
      get 'review'
    end
  end

  resources :posts do
    collection do
      post 'comment'
      get 'comment'


    end
  end 
  resources :categories
  
  resources :recipes do
    with_scope_level(:list) do
      get 'list/:category', :to => "recipes#list"
    end
    
    member do
      get 'review'
    end
  end
  
  resources :lists

  resources :friends do
  collection do
   get 'list'
   post 'list'
  end
  end


  resources :list_cats
  resources :vrattributes
  
  resources :reviews, :except => [:new,:index] do   
    with_scope_level(:new) do
      get 'new/:toreview', :to => "reviews#new"
   end
    with_scope_level(:index) do
      get 'index/:reviewed', :to => "reviews#index"
   end
   
   member do
     get 'edit'
   end
 end
  
  resources :vegresources, :except => [:new] do   
    with_scope_level(:new) do
      get 'new/:vrtype', :to => "vegresources#new"
   end
    
    member do
      get 'review'
      get 'highlight'
    end
 end

  match '/books'  => 'vegresources#books'
  match '/videos' => 'vegresources#videos'
  match '/websites' => 'vegresources#websites'
  match '/csas' => 'vegresources#csas'
  match '/grocery' => 'vegresources#grocery'
  match '/ristorantes' => 'vegresources#restaurants'
    
  match '/contact' => 'home#contact'
  
end

app/models/list_cat.rb
class ListCat < ActiveRecord::Base
end

app/controllers/list_cats_controller.rb
class ListCatsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /list_cats
  # GET /list_cats.xml
  def index
    @list_cats = ListCat.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @list_cats }
    end
  end

  # GET /list_cats/1
  # GET /list_cats/1.xml
  def show
    @list_cat = ListCat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @list_cat }
    end
  end

  # GET /list_cats/new
  # GET /list_cats/new.xml
  def new
    @list_cat = ListCat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @list_cat }
    end
  end

  # GET /list_cats/1/edit
  def edit
    @list_cat = ListCat.find(params[:id])
  end

  # POST /list_cats
  # POST /list_cats.xml
  def create
    @list_cat = ListCat.new(params[:list_cat])

    respond_to do |format|
      if @list_cat.save
        flash[:notice] = 'ListCat was successfully created.'
        format.html { redirect_to(:controller => 'list_cats', :action => 'edit', :id => @list_cat.id) }
        format.xml  { render :xml => @list_cat, :status => :created, :location => @list_cat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @list_cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /list_cats/1
  # PUT /list_cats/1.xml
  def update
    @list_cat = ListCat.find(params[:id])
    allcontacts = Friend.find(:all)   
     for acontact in allcontacts do
       list = List.find(:all,:conditions => "friend_id = #{acontact.id} and list_cat_id = #{@list_cat.id}")
       if params["#{acontact.id}"] == "on" and !list[0]
         list = List.new(:friend_id => acontact.id,:list_cat_id => @list_cat.id)
         list.save
       end
       if params["#{acontact.id}"] != "on" and list[0]
         list[0].destroy
       end
     end
    respond_to do |format|
      if @list_cat.update_attributes(params[:list_cat])
        flash[:notice] = 'ListCat was successfully updated.'
        format.html { redirect_to(:controller => 'list_cats', :action => 'edit', :id => @list_cat.id) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @list_cat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /list_cats/1
  # DELETE /list_cats/1.xml
  def destroy
    listentries = List.find(:all,:conditions => "list_cat_id = #{params[:id]}")
    for listentry in listentries 
      listentry.destroy
      end
    @list_cat = ListCat.find(params[:id])
    @list_cat.destroy

    respond_to do |format|
      format.html { redirect_to(:controller => 'lists') }
      format.xml  { head :ok }
    end
  end
end

app/views/list_cats/edit.html.erb
<h1>Editing <%=@list_cat.name%> list</h1>

<p> Note: This page allows you to change the name of this list, description and contacts on this list.  The list of contacts you see below is all of the VIGOR contacts.  Only the ones with check marks are on this list.  To add or remove, either check or uncheck the box.  If you'd like to view additional information or print lists of contact info go to the <%= link_to 'Contact Database', friends_path %> page.
<% form_for(@list_cat) do |f| %>
  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Description</b><br />
    <%= f.text_area :description, :size => "80X2"%>
  </p>
  
  <p><b>Add or remove contacts from this list:</b>
  <% allcontacts = Friend.find(:all,:order =>'lname')
  for acontact in allcontacts do%>
   <br><input type="checkbox"  name = "<%=acontact["id"]%>" 
   <%if List.find(:all,:conditions => "friend_id = #{acontact["id"]} and list_cat_id = #{@list_cat.id}" ).size >=1%>
   checked
   <%end%>
   ><%=acontact["fname"]%>&nbsp;<%=acontact["lname"]%></input>
 <% end %>
</p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Contact Database', friends_path %> &nbsp; &nbsp; &nbsp; &nbsp;
<%= link_to 'Administer Contact lists', :controller => 'lists'%>

app/views/list_cats/index.html.erb
<h1>Lists</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>

<% for list_cat in @list_cats %>
  <tr>
    <td><%=h list_cat.name %></td>
    <td><%=h list_cat.description %></td>
    <td><%= link_to 'Show', list_cat %></td>
    <td><%= link_to 'Edit', edit_list_cat_path(list_cat) %></td>
    <td><%= link_to 'Destroy', list_cat, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List', new_list_cat_path %> &nbsp; &nbsp; &nbsp; &nbsp;
<%= link_to 'Contacts Query Page', friends_path %> &nbsp; &nbsp; &nbsp; &nbsp;
<%= link_to 'Administer Contact lists', :controller => 'lists'%>

app/views/list_cats/new.html.erb
<h1>New List</h1>

<%= form_for(@list_cat) do |f| %>
  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Description</b><br />
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Contacts Query Page', friends_path %> &nbsp; &nbsp; &nbsp; &nbsp;
<%= link_to 'Administer Contact lists', :controller => 'lists'%>

app/views/list_cats/show.html.erb
<p>
  <b>Name:</b>
  <%=h @list_cat.name %>
</p>

<p>
  <b>Description:</b>
  <%=h @list_cat.description %>
</p>


<%= link_to 'Edit', edit_list_cat_path(@list_cat) %> |
<%= link_to 'Back', list_cats_path %>