config/routes.rb
Vigor::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  get "registrations/create"

  resources :vrhighlights

  resources :attachments

  resources :attatchments

  resources :restaurants

  resources :vegresources
  
  resources :home do
    collection do
      get 'send_email2list'
      get 'my_mailer'
      post 'send_email2list'
      post 'my_mailer'
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  
  devise_for :users, :controllers => { :registrations => "registrations" } do
    
   get "login", :to => "devise/sessions#new"
   delete "logout", :to => "devise/sessions#destroy"
   get "signup", :to => "devise/registrations#new"
   
  end
  
  resources :users do
   member do
     get 'removephoto'
     put 'addphoto'
     post 'addphoto'
   end
  end
  
  match "/users/:id/addphoto" => "users#addphoto", :via => [:post]
  match "/listrecipes/:by/:attr" => "recipes#list", :via => [:get]
  
  resources :events do
    collection do
      get 'calendar'
      post 'calendar'
      get 'copy'
      post 'list'
    end
    member do
      get 'review'
    end
  end

  resources :posts do
    collection do
      post 'comment'
      get 'comment'


    end
  end 
  resources :categories
  
  resources :recipes do
    with_scope_level(:list) do
      get 'list/:category', :to => "recipes#list"
    end
    
    member do
      get 'review'
    end
  end
  
  resources :lists

  resources :friends do
  collection do
   get 'list'
   post 'list'
  end
  end


  resources :list_cats
  resources :vrattributes
  
  resources :reviews, :except => [:new,:index] do   
    with_scope_level(:new) do
      get 'new/:toreview', :to => "reviews#new"
   end
    with_scope_level(:index) do
      get 'index/:reviewed', :to => "reviews#index"
   end
   
   member do
     get 'edit'
   end
 end
  
  resources :vegresources, :except => [:new] do   
    with_scope_level(:new) do
      get 'new/:vrtype', :to => "vegresources#new"
   end
    
    member do
      get 'review'
      get 'highlight'
    end
 end

  match '/books'  => 'vegresources#books'
  match '/videos' => 'vegresources#videos'
  match '/websites' => 'vegresources#websites'
  match '/csas' => 'vegresources#csas'
  match '/grocery' => 'vegresources#grocery'
  match '/ristorantes' => 'vegresources#restaurants'
    
  match '/contact' => 'home#contact'
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews
  has_many :attachments, :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  accepts_nested_attributes_for :reviews, :allow_destroy => true
  attr_accessible :name, :attachments_attributes, :reviews_attributes, :category_id, :description, :ingredients, :instructions

   
   def rating
    reviews.select("avg(rating) as average").first.average.to_i
   end
  
   def self.featured
     Recipe.joins(:attachments).order("recipes.created_at DESC").first
   end
   
   def self.newest(quantity)
     Recipe.includes(:attachments).order("recipes.created_at DESC").limit(quantity) unless Recipe.includes(:attachments).blank?
   end
   
   def self.find_by_potluck(month,year)
     Recipe.where(create_at.month == month && create_at.year == year)
   end
   
   def self.find_by_rating(stars)
     Recipe.where(rating == stars)
   end
   
   
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.xml
   before_filter :authenticate_user!, :only => [ :edit, :new, :update ]
   load_and_authorize_resource
   layout '/layouts/recipe'
   
  def index
    if params[:category_id].nil?
      @recipes = Recipe.find(:all)
    else
      @recipes = Recipe.find(:all,
                            :conditions => ["category_id = ?", params[:category_id]])
      params[:category_id] = nil
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recipes }
    end
  end
 # GET /recipes/1/review
  def review
    @recipe = Recipe.find(params[:id])
  end
   
  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.xml
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  def list
 #   rcat = "1 = 0"
#if params[:all] then rcat = "1 = 1" end
#if params[:rcat] then params[:rcat].each_value {|category| rcat += " or category_id = #{category}" } end
#@from = Time.new(params["from(1i)"].to_i, 10, 1)
#@to = Time.new(2013, 10, 31)
#@recipes_list = Recipe.find_by_sql ["SELECT * FROM recipes WHERE (#{rcat}) and created_at >= ? and created_at <= ?",@from,@to]
#@recipes_list = Recipe.find_all_by_category_id(params[:category])
@by = params[:by]
@attr = params[:attr] 
case @by
when "author"
  @recipes_list = Recipe.joins(:user).where("users.name = ?",@attr)
when "category"
  @recipes_list = Recipe.find_all_by_category_id(@attr)
when "ingredient"
  @recipes_list = Recipe.where("ingredients LIKE ?",'%' + @attr + '%')
when "rating"
  @recipes_list = Recipe.find_by_rating(@attr)
when "potluck"
  @recipes_list = Recipe.find_by_potluck(@attr)
else
  @recipes_list = Recipe.newest(5)
end

end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.xml
  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.user_id = current_user.id
   
    respond_to do |format|
      if @recipe.save
        flash[:notice] = 'Recipe was successfully created.'
        format.html { redirect_to(@recipe) }
        format.xml  { render :xml => @recipe, :status => :created, :location => @recipe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.xml
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        flash[:notice] = 'Recipe was successfully updated.'
        format.html { redirect_to(@recipe) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.xml
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to(recipes_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/recipes/Copy of index.html.erb
<p style="float:right">
	<script type="text/javascript">
  $('[data-behaviour~=datepicker]').datepicker()
</script>

<% if can? :create, Recipe %>
<%= link_to 'New recipe', new_recipe_path %>
<% end %>
</p>
<h2> New Recipes </h2>
<%@recipes_list = Recipe.find_by_sql ["SELECT * FROM recipes WHERE created_at >= ? and created_at <= ?",Time.now()-4*7*24*60*60,Time.now()]%>

<table>

<% for recipe in @recipes_list %>
  <tr>
    <td><%= link_to "#{recipe.title}", recipe %>
	</td>
    <td>
    	(<%= recipe.category.name if recipe.category%>)
    </td>
    <td>
    	<%= h recipe.created_at.strftime("%b %d, %Y") %>
		
    </td>
  </tr>
  </table>
<% end %>
<!--<h2> Featured </h2>-->
<h2> List by Category and Date Posted </h2>
        
 <%= simple_form_for :recipe ,:url => '/recipes/list' do |f| %>
  <%= f.input :from, as: :date, start_year: Date.today.year - 20,
                              end_year: Date.today.year , discard_day: true,
                              order: [:month, :year] %>
  <%= f.input :to, as: :date, start_year: Date.today.year - 20,
                              end_year: Date.today.year , discard_day: true,
                              order: [:month, :year] %>                                                           
                       
	
	<%= f.button :submit, 'Search'%>  

	<br>Categories:
    <div width = 70px>
    
    
  <%@list_categories = Category.find_by_sql ["select * from categories"]%>
  <input type="checkbox" name = "all" checked>All Categories</input>
  <% for category in @list_categories do%>
  <br><input type="checkbox"  name = "rcat[<%=category["id"]%>]" value="<%=category["id"]%>" ><%=category["name"]%></input>
<% end %>
    
		</div>
	
  <% end %>


<br />

app/views/recipes/_form.html.erb
<p>
   <b>Title</b><br />
   <%= f.text_field :name %>
 </p>

<p><b>Category</b><br/>
<%= select("recipe", "category_id", Category.find(:all).collect{ |c| [ c.name, c.id] }) %>
</p>

 <p>
   <b>Description</b><br />
   <%= f.cktext_area :description, :size => "50x2" %>
 </p>

 <p>
   <b>Ingredients</b><br />
   <%= f.cktext_area :ingredients,  :size => "50x20"  %>
 </p>
 
 <p>
   <b>Instructions</b><br />
   <%= f.cktext_area :instructions, :size => "70x15"  %>
 </p>
 <p>
   <%= f.submit button%>
 </p>

app/views/recipes/_navbar.html.erb

<%
@ingredients = ['CHOCOLATE','BEANS','TOFU','MUSHROOMS','PASTA','RICE','LENTILS','POTATOES','CASHEWS','SEITAN','PUMPKIN','TEMPEH','GINGER','POTATO','CHICKPEAS','AVOCADO','COCONUT MILK','BASIL','WALNUTS','ALMONDS','CILANTRO','PINENUTS','APPLES','CHOCOLATE CHIPS','QUINOA']
@categories = Category.find_by_sql ["select * from categories"]
#@potlucks = ['January 2013','February 2013','March 2013']
#@ratings = ['*','**','***','****','*****']
@authors = User.joins(:recipes).select("DISTINCT users.name")%>
<div class="nav nav-tabs nav-stacked" style="width:100%">
	<div class="row-fluid" >
		<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
		
			<!-- Be sure to leave the brand out there if you want it shown -->
  
  <!-- Everything you want hidden at 940px or less, place within here -->
  <div>
  	<!-- .nav, .navbar-search, .navbar-form, etc -->
 <ul class="btn-group btn-group-vertical nav" style="margin-top:.5em;">
 	
 	<!-- Ingredients -->
<li class="btn dropdown"> <a href="#" class="active dropdown-toggle" data-toggle="dropdown">Ingredients    
	<b class="caret"></b>   </a>
	<ul class="dropdown-menu">
    <% @ingredients.each do |item|%>
    <li><%= link_to item, '/listrecipes/ingredient/' + item, :tabindex => -1 %> </li>
    <%end%>
</ul>
</li>

 	<!-- Categories -->
<li class="btn dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories   
	<b class="caret"></b>   </a>
	<ul class="dropdown-menu">
    <% @categories.each do |category|%>
    <li><%= link_to category.name, '/listrecipes/category/' + category.id.to_s, :tabindex => -1 %> </li>
    <%end%>
</ul>
</li>

 	<!-- Potlucks -->


 	<!-- Ratings -->


 	<!-- Authors -->
<li class="btn dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Authors    
	<b class="caret"></b>   </a>
	<ul class="dropdown-menu">
    <% @authors.each do |item|%>
    <li><%= link_to item.name,  '/listrecipes/author/' + item.name, :tabindex => -1 %> </li>
    <%end%>
</ul>
</li>


</ul> 
   </div>
 
   </div>
   </div>
   

app/views/recipes/_show.html.erb
<%@recipe = recipe%>
<h2 class="title"><%=h @recipe.name %></h2>
<%=render :partial => '/layouts/like', :locals => {:likeurl => recipe_url(@recipe)}%>	

<%=image_tag @recipe.attachments.first.photo unless @recipe.attachments.blank?%>
<p>
<% @recipe.rating.times do%><%=image_tag('/assets/star.jpg',:style => "width:2.5em")%> <%end%>(<%=@recipe.reviews.size%> reviews)
</p>
<% if can? :create, Vegresource %>
<p><%= link_to 'Write Review', review_recipe_path(@recipe), :class => "btn btn-primary"  %></p>
<% elsif !user_signed_in? %>
<%= render :partial => '/users/signup', :locals => {:message => "to get access to review recipes."}%>
<%end%>

  
<div class="content">
  <%= @recipe.description.html_safe%>
</div>

<div class="content">
  <%= @recipe.ingredients.html_safe %>
</div>

<div class="content">
  <%= @recipe.instructions.html_safe %>
</div>

  <%= render :partial => '/attachments/view', :locals => {:object => @recipe} %>

<%if @recipe.user%>
<%=render :partial => '/users/profilethumb', :locals => {:user => @recipe.user}%>
<%end%>

<% if can? :create, Recipe %>
<%= render :partial => '/attachments/form', :locals => {:object => @recipe} %>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<% elsif !user_signed_in? %>
<%= render :partial => '/users/signup', :locals => {:message => "to get access to post recipes!"}%>
<%end%>
<% if can? :manage, Recipe %>
<%= link_to 'Delete',  @recipe, :confirm => 'Are you sure?', :method => :delete  %> 
|

<% end %>
<%= link_to 'Back', recipes_path %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>
<% if can? :create, Recipe %>

<%= simple_form_for(@recipe) do |f| %>
  <%= render :partial => "form", :locals => { :f => f, :button => "Update"  }  %>
<% end %>
<% else %>
  <p><strong>You are currently not logged in.</strong></p>
  <p>
    <%= link_to 'Login', login_path %> or
    <%= link_to 'Sign Up', signup_path %>
  </p>
<% end %>
<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
	<%@featured = Recipe.featured%>
	<%=render :partial => '/recipes/show', :locals => {:recipe => @featured} if @featured%>

app/views/recipes/list.html.erb
<div class="row-fluid">

<span class="span9"> 
<% unless @recipes_list.blank?%>
<% @recipes_list.each do |recipe| %>
  <div class="row-fluid"> 
  	
  	  <span class="span4">
    <%= link_to image_tag(recipe.attachments.first.photo.url(:small)), recipe unless recipe.attachments.blank?%>	
    </span>
    
    <span class="span4">
    	
    <h3><%= link_to "#{recipe.name}", recipe %></h3>
    <% unless recipe.created_at.blank? %>
    <%= h recipe.created_at.strftime("%b %d, %Y") %>	
    <% end %>
    </span>
    
    <span class="span4">
    	
    </span>
    
  
    
	
   </div>
<% end %>
<% end %>
</span>
</div>

app/views/recipes/new.html.erb
<h1>Add Recipe</h1>
<%= simple_form_for(@recipe) do |f| %>
 <%= render :partial => "form", :locals => { :f => f, :button => "Create"  }  %>
<% end %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/review.html.erb
Review <%=@recipe.name%>
<%= render :partial => '/reviews/form', :locals => {:object => @recipe} %>

app/views/recipes/show.html.erb
<%=render :partial => '/recipes/show', :locals => {:recipe => @recipe}%>